name: rfx

on: ["push"]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: "18"
          cache: "yarn"
          cache-dependency-path: "./yarn.lock"
      - run: yarn install
      - run: yarn lint

  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: "18"
          cache: "yarn"
          cache-dependency-path: "./yarn.lock"
      - run: yarn install
      - run: |
          echo REPORT_GAS=${{ secrets.REPORT_GAS }} >> .env
          echo ARBISCAN_API_KEY=${{ secrets.ARBISCAN_API_KEY }} >> .env
          echo ACCOUNT_KEY=${{ secrets.ACCOUNT_KEY }} >> .env
          yarn test
